% triple_cycler_ga.m

venus = planet_properties(2);
earth = planet_properties(3);
mars = planet_properties(4);

constants = struct(...
    'mu_sun', 1.32712440018e11, ...  % Solar GM [km^3/s^2]
    'mu_venus', venus.mu, ...
    'mu_earth', earth.mu, ...
    'mu_mars', mars.mu, ...
    'R_venus', venus.radius, ...
    'R_earth', earth.radius, ...
    'R_mars', mars.radius, ...
    'synodic_period', 32/5*365.25*86400); % Synodic period [s]

constraints = struct(...
    'alt_min', 300, ...                    % Minimum flyby altitude [km]
    'alt_max', 100000, ...                 % Maximum flyby altitude
    'vinf_max', 12, ...                    % Maximum v-infinity [km/s] 
    'vinf_min', 2, ...                     % Minimum v-infinity [km/s]
    'tof_min', 100*86400, ...             % Minimum transfer time [s]
    'tof_max', 500*86400, ...             % Maximum transfer time [s]
    'pos_tol', 1e-3, ...                  % Position matching tolerance [km]
    'vel_tol', 1e-6);                     % Velocity matching tolerance [km/s]

% GA Parameters
num_dates = 6;  % Number of encounter dates
chromosome_length = num_dates*6 + (num_dates-1)*2;  % dates + b-plane params

bounds = struct(...
    'date_min', J0(2010, 1, 1), ...
    'date_max', J0(2050, 1, 1), ...
    'bmag_min', 1e3, ...
    'bmag_max', 1e5, ...
    'bang_min', -pi, ...
    'bang_max', pi);

% Setup Parallel Pool
delete(gcp('nocreate'));
parpool('local', feature('numcores'));

options = optimoptions('ga', ...
    'PopulationSize', 100, ...
    'MaxGenerations', 50, ...
    'CrossoverFraction', 0.8, ...
    'MutationFcn', @mutationadaptfeasible, ...
    'CrossoverFcn', @crossoverscattered, ...
    'SelectionFcn', @selectiontournament, ...
    'Display', 'iter', ...
    'UseParallel', true, ...
    'CreationFcn', @createInitialPopulation, ...
    'FitnessLimit', 1e-6, ...
    'FunctionTolerance', 1e-4, ...
    'TolCon', 1e-4, ...
    'InitialPopulation', [], ...
    'NonlinearConstraintAlgorithm', 'auglag');

% Define Variable Bounds
lb = [repmat(bounds.date_min, 1, num_dates), ...      % 6 dates
      repmat([bounds.bmag_min, bounds.bang_min], 1, 5)]; % 5 B-plane parameter pairs

ub = [repmat(bounds.date_max, 1, num_dates), ...      % 6 dates
      repmat([bounds.bmag_max, bounds.bang_max], 1, 5)]; % 5 B-plane parameter pairs

% In triple_cycler_ga.m before GA call:
fprintf('Lower bounds: ');
fprintf('%.2f ', lb);
fprintf('\nUpper bounds: ');
fprintf('%.2f ', ub);
fprintf('\n');

% Check CreationFcn output:
test_pop = createInitialPopulation(16, [], options);
fprintf('Sample initial population first row:\n');
fprintf('Dates: ');
fprintf('%.2f ', test_pop(1,1:6));
fprintf('\nB-parameters: ');
fprintf('%.2f ', test_pop(1,7:end));
fprintf('\n');

% Run GA
[x_best, fval, exitflag, output] = ga(...
    @(x)fitnessFunction(x, constants, constraints), ...
    chromosome_length, [], [], [], [], lb, ub, ...
    @(x)nonlinearConstraints(x, constants, constraints), ...
    [], options);

% Process and Save Results
solution = processSolution(x_best, constants, constraints);
save('cycler_solution.mat', 'solution', 'constants', 'constraints', ...
     'x_best', 'fval', 'output');

% Display Results Summary
displaySolution(solution);